export const LIVE_CHAT_SOCKET_EVENTS = {
  MESSAGES: {
    NEW_MESSAGE: "NEW_MESSAGE",
    UPDATE_MESSAGE: "UPDATE_MESSAGE",
    DELETE_MESSAGE: "DELETE_MESSAGE",
  },
};
export const NOTIFICATION_SOCKET_EVENTS = {
  NOTIFICATION: {
    NEW_NOTIFICATION: "NEW_NOTIFICATION",
    UPDATE_MESSAGE: "UPDATE_MESSAGE",
    DELETE_MESSAGE: "DELETE_MESSAGE",
  },
};
