import { USERROLE } from "./roles";
import { PERMISSION } from "./permissions";

export const ROLE_PERMISSIONS: Record<USERROLE, PERMISSION[]> = {
  [USERROLE.ADMIN]: [
    // Account
    PERMISSION.ACCOUNT_VIEW,
    PERMISSION.ACCOUNT_CREATE,
    PERMISSION.ACCOUNT_DELETE,
    PERMISSION.ACCOUNT_ASSIGN,

    // Lead
    PERMISSION.LEAD_VIEW,
    PERMISSION.LEAD_CREATE,
    PERMISSION.LEAD_DELETE,

    // User
    // PERMISSION.USER_MANAGE,
  ],

  [USERROLE.ACCOUNT_MANAGER]: [
    // Account
    PERMISSION.ACCOUNT_VIEW,
    PERMISSION.ACCOUNT_CREATE,

    // Lead
    PERMISSION.LEAD_VIEW,
    PERMISSION.LEAD_CREATE,
  ],

  [USERROLE.TEAM_MEMBER]: [
    // Read-only
    PERMISSION.ACCOUNT_VIEW,
    PERMISSION.LEAD_VIEW,
  ],

  [USERROLE.LEAD_MANAGER]: [
    PERMISSION.LEAD_VIEW,
    PERMISSION.LEAD_CREATE,
    PERMISSION.LEAD_DELETE,
  ],
};
